export const legacy=[
    {
        "Timezone":"Africa/Abidjan",
        "Country":"Abidjan"
    },
    {
        "Timezone":"Africa/Accra",
        "Country":"Accra"
    },
    {
        "Timezone":"Africa/Addis_Ababa",
        "Country":"Addis Ababa"
    },
    {
        "Timezone":"Africa/Algiers",
        "Country":"Algiers"
    },
    {
        "Timezone":"Africa/Asmara",
        "Country":"Asmara"
    },
    {
        "Timezone":"Africa/Asmera",
        "Country":"Asmera"
    },
    {
        "Timezone":"Africa/Bamako",
        "Country":"Bamako"
    },
    {
        "Timezone":"Africa/Bangui",
        "Country":"Bangui"
    },
    {
        "Timezone":"Africa/Banjul",
        "Country":"Banjul"
    },
    {
        "Timezone":"Africa/Bissau",
        "Country":"Bissau"
    },
    {
        "Timezone":"Africa/Blantyre",
        "Country":"Blantyre"
    },
    {
        "Timezone":"Africa/Brazzaville",
        "Country":"Brazzaville"
    },
    {
        "Timezone":"Africa/Bujumbura",
        "Country":"Bujumbura"
    },
    {
        "Timezone":"Africa/Cairo",
        "Country":"Cairo"
    },
    {
        "Timezone":"Africa/Casablanca",
        "Country":"Casablanca"
    },
    {
        "Timezone":"Africa/Ceuta",
        "Country":"Ceuta"
    },
    {
        "Timezone":"Africa/Conakry",
        "Country":"Conakry"
    },
    {
        "Timezone":"Africa/Dakar",
        "Country":"Dakar"
    },
    {
        "Timezone":"Africa/Dar_es_Salaam",
        "Country":"Dar es Salaam"
    },
    {
        "Timezone":"Africa/Djibouti",
        "Country":"Djibouti"
    },
    {
        "Timezone":"Africa/Douala",
        "Country":"Douala"
    },
    {
        "Timezone":"Africa/El_Aaiun",
        "Country":"El Aaiun"
    },
    {
        "Timezone":"Africa/Freetown",
        "Country":"Freetown"
    },
    {
        "Timezone":"Africa/Gaborone",
        "Country":"Gaborone"
    },
    {
        "Timezone":"Africa/Harare",
        "Country":"Harare"
    },
    {
        "Timezone":"Africa/Johannesburg",
        "Country":"Johannesburg"
    },
    {
        "Timezone":"Africa/Juba",
        "Country":"Juba"
    },
    {
        "Timezone":"Africa/Kampala",
        "Country":"Kampala"
    },
    {
        "Timezone":"Africa/Khartoum",
        "Country":"Khartoum"
    },
    {
        "Timezone":"Africa/Kigali",
        "Country":"Kigali"
    },
    {
        "Timezone":"Africa/Kinshasa",
        "Country":"Kinshasa"
    },
    {
        "Timezone":"Africa/Lagos",
        "Country":"Lagos"
    },
    {
        "Timezone":"Africa/Libreville",
        "Country":"Libreville"
    },
    {
        "Timezone":"Africa/Lome",
        "Country":"Lome"
    },
    {
        "Timezone":"Africa/Luanda",
        "Country":"Luanda"
    },
    {
        "Timezone":"Africa/Lubumbashi",
        "Country":"Lubumbashi"
    },
    {
        "Timezone":"Africa/Lusaka",
        "Country":"Lusaka"
    },
    {
        "Timezone":"Africa/Malabo",
        "Country":"Malabo"
    },
    {
        "Timezone":"Africa/Maputo",
        "Country":"Maputo"
    },
    {
        "Timezone":"Africa/Maseru",
        "Country":"Maseru"
    },
    {
        "Timezone":"Africa/Mbabane",
        "Country":"Mbabane"
    },
    {
        "Timezone":"Africa/Mogadishu",
        "Country":"Mogadishu"
    },
    {
        "Timezone":"Africa/Monrovia",
        "Country":"Monrovia"
    },
    {
        "Timezone":"Africa/Nairobi",
        "Country":"Nairobi"
    },
    {
        "Timezone":"Africa/Ndjamena",
        "Country":"Ndjamena"
    },
    {
        "Timezone":"Africa/Niamey",
        "Country":"Niamey"
    },
    {
        "Timezone":"Africa/Nouakchott",
        "Country":"Nouakchott"
    },
    {
        "Timezone":"Africa/Ouagadougou",
        "Country":"Ouagadougou"
    },
    {
        "Timezone":"Africa/Porto-Novo",
        "Country":"Porto-Novo"
    },
    {
        "Timezone":"Africa/Sao_Tome",
        "Country":"Sao Tome"
    },
    {
        "Timezone":"Africa/Timbuktu",
        "Country":"Timbuktu"
    },
    {
        "Timezone":"Africa/Tripoli",
        "Country":"Tripoli"
    },
    {
        "Timezone":"Africa/Tunis",
        "Country":"Tunis"
    },
    {
        "Timezone":"Africa/Windhoek",
        "Country":"Windhoek"
    },
    {
        "Timezone":"America/Adak",
        "Country":"Adak"
    },
    {
        "Timezone":"America/Anchorage",
        "Country":"Anchorage"
    },
    {
        "Timezone":"America/Anguilla",
        "Country":"Anguilla"
    },
    {
        "Timezone":"America/Antigua",
        "Country":"Antigua"
    },
    {
        "Timezone":"America/Araguaina",
        "Country":"Araguaina"
    },
    {
        "Timezone":"America/Argentina/Buenos_Aires",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Catamarca",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/ComodRivadavia",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Cordoba",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Jujuy",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/La_Rioja",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Mendoza",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Rio_Gallegos",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Salta",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/San_Juan",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/San_Luis",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Tucuman",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Argentina/Ushuaia",
        "Country":"Argentina"
    },
    {
        "Timezone":"America/Aruba",
        "Country":"Aruba"
    },
    {
        "Timezone":"America/Asuncion",
        "Country":"Asuncion"
    },
    {
        "Timezone":"America/Atikokan",
        "Country":"Atikokan"
    },
    {
        "Timezone":"America/Atka",
        "Country":"Atka"
    },
    {
        "Timezone":"America/Bahia",
        "Country":"Bahia"
    },
    {
        "Timezone":"America/Bahia_Banderas",
        "Country":"Bahia Banderas"
    },
    {
        "Timezone":"America/Barbados",
        "Country":"Barbados"
    },
    {
        "Timezone":"America/Belem",
        "Country":"Belem"
    },
    {
        "Timezone":"America/Belize",
        "Country":"Belize"
    },
    {
        "Timezone":"America/Blanc-Sablon",
        "Country":"Blanc-Sablon"
    },
    {
        "Timezone":"America/Boa_Vista",
        "Country":"Boa Vista"
    },
    {
        "Timezone":"America/Bogota",
        "Country":"Bogota"
    },
    {
        "Timezone":"America/Boise",
        "Country":"Boise"
    },
    {
        "Timezone":"America/Buenos_Aires",
        "Country":"Buenos Aires"
    },
    {
        "Timezone":"America/Cambridge_Bay",
        "Country":"Cambridge Bay"
    },
    {
        "Timezone":"America/Campo_Grande",
        "Country":"Campo Grande"
    },
    {
        "Timezone":"America/Cancun",
        "Country":"Cancun"
    },
    {
        "Timezone":"America/Caracas",
        "Country":"Caracas"
    },
    {
        "Timezone":"America/Catamarca",
        "Country":"Catamarca"
    },
    {
        "Timezone":"America/Cayenne",
        "Country":"Cayenne"
    },
    {
        "Timezone":"America/Cayman",
        "Country":"Cayman"
    },
    {
        "Timezone":"America/Chicago",
        "Country":"Chicago"
    },
    {
        "Timezone":"America/Chihuahua",
        "Country":"Chihuahua"
    },
    {
        "Timezone":"America/Ciudad_Juarez",
        "Country":"Ciudad Juarez"
    },
    {
        "Timezone":"America/Coral_Harbour",
        "Country":"Coral Harbour"
    },
    {
        "Timezone":"America/Cordoba",
        "Country":"Cordoba"
    },
    {
        "Timezone":"America/Costa_Rica",
        "Country":"Costa Rica"
    },
    {
        "Timezone":"America/Creston",
        "Country":"Creston"
    },
    {
        "Timezone":"America/Cuiaba",
        "Country":"Cuiaba"
    },
    {
        "Timezone":"America/Curacao",
        "Country":"Curacao"
    },
    {
        "Timezone":"America/Danmarkshavn",
        "Country":"Danmarkshavn"
    },
    {
        "Timezone":"America/Dawson",
        "Country":"Dawson"
    },
    {
        "Timezone":"America/Dawson_Creek",
        "Country":"Dawson Creek"
    },
    {
        "Timezone":"America/Denver",
        "Country":"Denver"
    },
    {
        "Timezone":"America/Detroit",
        "Country":"Detroit"
    },
    {
        "Timezone":"America/Dominica",
        "Country":"Dominica"
    },
    {
        "Timezone":"America/Edmonton",
        "Country":"Edmonton"
    },
    {
        "Timezone":"America/Eirunepe",
        "Country":"Eirunepe"
    },
    {
        "Timezone":"America/El_Salvador",
        "Country":"El Salvador"
    },
    {
        "Timezone":"America/Ensenada",
        "Country":"Ensenada"
    },
    {
        "Timezone":"America/Fort_Nelson",
        "Country":"Fort Nelson"
    },
    {
        "Timezone":"America/Fort_Wayne",
        "Country":"Fort Wayne"
    },
    {
        "Timezone":"America/Fortaleza",
        "Country":"Fortaleza"
    },
    {
        "Timezone":"America/Glace_Bay",
        "Country":"Glace Bay"
    },
    {
        "Timezone":"America/Godthab",
        "Country":"Godthab"
    },
    {
        "Timezone":"America/Goose_Bay",
        "Country":"Goose Bay"
    },
    {
        "Timezone":"America/Grand_Turk",
        "Country":"Grand Turk"
    },
    {
        "Timezone":"America/Grenada",
        "Country":"Grenada"
    },
    {
        "Timezone":"America/Guadeloupe",
        "Country":"Guadeloupe"
    },
    {
        "Timezone":"America/Guatemala",
        "Country":"Guatemala"
    },
    {
        "Timezone":"America/Guayaquil",
        "Country":"Guayaquil"
    },
    {
        "Timezone":"America/Guyana",
        "Country":"Guyana"
    },
    {
        "Timezone":"America/Halifax",
        "Country":"Halifax"
    },
    {
        "Timezone":"America/Havana",
        "Country":"Havana"
    },
    {
        "Timezone":"America/Hermosillo",
        "Country":"Hermosillo"
    },
    {
        "Timezone":"America/Indiana/Indianapolis",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Knox",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Marengo",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Petersburg",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Tell_City",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Vevay",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Vincennes",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indiana/Winamac",
        "Country":"Indiana"
    },
    {
        "Timezone":"America/Indianapolis",
        "Country":"Indianapolis"
    },
    {
        "Timezone":"America/Inuvik",
        "Country":"Inuvik"
    },
    {
        "Timezone":"America/Iqaluit",
        "Country":"Iqaluit"
    },
    {
        "Timezone":"America/Jamaica",
        "Country":"Jamaica"
    },
    {
        "Timezone":"America/Jujuy",
        "Country":"Jujuy"
    },
    {
        "Timezone":"America/Juneau",
        "Country":"Juneau"
    },
    {
        "Timezone":"America/Kentucky/Louisville",
        "Country":"Kentucky"
    },
    {
        "Timezone":"America/Kentucky/Monticello",
        "Country":"Kentucky"
    },
    {
        "Timezone":"America/Knox_IN",
        "Country":"Knox IN"
    },
    {
        "Timezone":"America/Kralendijk",
        "Country":"Kralendijk"
    },
    {
        "Timezone":"America/La_Paz",
        "Country":"La Paz"
    },
    {
        "Timezone":"America/Lima",
        "Country":"Lima"
    },
    {
        "Timezone":"America/Los_Angeles",
        "Country":"Los Angeles"
    },
    {
        "Timezone":"America/Louisville",
        "Country":"Louisville"
    },
    {
        "Timezone":"America/Lower_Princes",
        "Country":"Lower Princes"
    },
    {
        "Timezone":"America/Maceio",
        "Country":"Maceio"
    },
    {
        "Timezone":"America/Managua",
        "Country":"Managua"
    },
    {
        "Timezone":"America/Manaus",
        "Country":"Manaus"
    },
    {
        "Timezone":"America/Marigot",
        "Country":"Marigot"
    },
    {
        "Timezone":"America/Martinique",
        "Country":"Martinique"
    },
    {
        "Timezone":"America/Matamoros",
        "Country":"Matamoros"
    },
    {
        "Timezone":"America/Mazatlan",
        "Country":"Mazatlan"
    },
    {
        "Timezone":"America/Mendoza",
        "Country":"Mendoza"
    },
    {
        "Timezone":"America/Menominee",
        "Country":"Menominee"
    },
    {
        "Timezone":"America/Merida",
        "Country":"Merida"
    },
    {
        "Timezone":"America/Metlakatla",
        "Country":"Metlakatla"
    },
    {
        "Timezone":"America/Mexico_City",
        "Country":"Mexico City"
    },
    {
        "Timezone":"America/Miquelon",
        "Country":"Miquelon"
    },
    {
        "Timezone":"America/Moncton",
        "Country":"Moncton"
    },
    {
        "Timezone":"America/Monterrey",
        "Country":"Monterrey"
    },
    {
        "Timezone":"America/Montevideo",
        "Country":"Montevideo"
    },
    {
        "Timezone":"America/Montreal",
        "Country":"Montreal"
    },
    {
        "Timezone":"America/Montserrat",
        "Country":"Montserrat"
    },
    {
        "Timezone":"America/Nassau",
        "Country":"Nassau"
    },
    {
        "Timezone":"America/New_York",
        "Country":"New York"
    },
    {
        "Timezone":"America/Nipigon",
        "Country":"Nipigon"
    },
    {
        "Timezone":"America/Nome",
        "Country":"Nome"
    },
    {
        "Timezone":"America/Noronha",
        "Country":"Noronha"
    },
    {
        "Timezone":"America/North_Dakota/Beulah",
        "Country":"North Dakota"
    },
    {
        "Timezone":"America/North_Dakota/Center",
        "Country":"North Dakota"
    },
    {
        "Timezone":"America/North_Dakota/New_Salem",
        "Country":"North Dakota"
    },
    {
        "Timezone":"America/Nuuk",
        "Country":"Nuuk"
    },
    {
        "Timezone":"America/Ojinaga",
        "Country":"Ojinaga"
    },
    {
        "Timezone":"America/Panama",
        "Country":"Panama"
    },
    {
        "Timezone":"America/Pangnirtung",
        "Country":"Pangnirtung"
    },
    {
        "Timezone":"America/Paramaribo",
        "Country":"Paramaribo"
    },
    {
        "Timezone":"America/Phoenix",
        "Country":"Phoenix"
    },
    {
        "Timezone":"America/Port-au-Prince",
        "Country":"Port-au-Prince"
    },
    {
        "Timezone":"America/Port_of_Spain",
        "Country":"Port of Spain"
    },
    {
        "Timezone":"America/Porto_Acre",
        "Country":"Porto Acre"
    },
    {
        "Timezone":"America/Porto_Velho",
        "Country":"Porto Velho"
    },
    {
        "Timezone":"America/Puerto_Rico",
        "Country":"Puerto Rico"
    },
    {
        "Timezone":"America/Punta_Arenas",
        "Country":"Punta Arenas"
    },
    {
        "Timezone":"America/Rainy_River",
        "Country":"Rainy River"
    },
    {
        "Timezone":"America/Rankin_Inlet",
        "Country":"Rankin Inlet"
    },
    {
        "Timezone":"America/Recife",
        "Country":"Recife"
    },
    {
        "Timezone":"America/Regina",
        "Country":"Regina"
    },
    {
        "Timezone":"America/Resolute",
        "Country":"Resolute"
    },
    {
        "Timezone":"America/Rio_Branco",
        "Country":"Rio Branco"
    },
    {
        "Timezone":"America/Rosario",
        "Country":"Rosario"
    },
    {
        "Timezone":"America/Santa_Isabel",
        "Country":"Santa Isabel"
    },
    {
        "Timezone":"America/Santarem",
        "Country":"Santarem"
    },
    {
        "Timezone":"America/Santiago",
        "Country":"Santiago"
    },
    {
        "Timezone":"America/Santo_Domingo",
        "Country":"Santo Domingo"
    },
    {
        "Timezone":"America/Sao_Paulo",
        "Country":"Sao Paulo"
    },
    {
        "Timezone":"America/Scoresbysund",
        "Country":"Scoresbysund"
    },
    {
        "Timezone":"America/Shiprock",
        "Country":"Shiprock"
    },
    {
        "Timezone":"America/Sitka",
        "Country":"Sitka"
    },
    {
        "Timezone":"America/St_Barthelemy",
        "Country":"St Barthelemy"
    },
    {
        "Timezone":"America/St_Johns",
        "Country":"St Johns"
    },
    {
        "Timezone":"America/St_Kitts",
        "Country":"St Kitts"
    },
    {
        "Timezone":"America/St_Lucia",
        "Country":"St Lucia"
    },
    {
        "Timezone":"America/St_Thomas",
        "Country":"St Thomas"
    },
    {
        "Timezone":"America/St_Vincent",
        "Country":"St Vincent"
    },
    {
        "Timezone":"America/Swift_Current",
        "Country":"Swift Current"
    },
    {
        "Timezone":"America/Tegucigalpa",
        "Country":"Tegucigalpa"
    },
    {
        "Timezone":"America/Thule",
        "Country":"Thule"
    },
    {
        "Timezone":"America/Thunder_Bay",
        "Country":"Thunder Bay"
    },
    {
        "Timezone":"America/Tijuana",
        "Country":"Tijuana"
    },
    {
        "Timezone":"America/Toronto",
        "Country":"Toronto"
    },
    {
        "Timezone":"America/Tortola",
        "Country":"Tortola"
    },
    {
        "Timezone":"America/Vancouver",
        "Country":"Vancouver"
    },
    {
        "Timezone":"America/Virgin",
        "Country":"Virgin"
    },
    {
        "Timezone":"America/Whitehorse",
        "Country":"Whitehorse"
    },
    {
        "Timezone":"America/Winnipeg",
        "Country":"Winnipeg"
    },
    {
        "Timezone":"America/Yakutat",
        "Country":"Yakutat"
    },
    {
        "Timezone":"America/Yellowknife",
        "Country":"Yellowknife"
    },
    {
        "Timezone":"Antarctica/Casey",
        "Country":"Casey"
    },
    {
        "Timezone":"Antarctica/Davis",
        "Country":"Davis"
    },
    {
        "Timezone":"Antarctica/DumontDUrville",
        "Country":"DumontDUrville"
    },
    {
        "Timezone":"Antarctica/Macquarie",
        "Country":"Macquarie"
    },
    {
        "Timezone":"Antarctica/Mawson",
        "Country":"Mawson"
    },
    {
        "Timezone":"Antarctica/McMurdo",
        "Country":"McMurdo"
    },
    {
        "Timezone":"Antarctica/Palmer",
        "Country":"Palmer"
    },
    {
        "Timezone":"Antarctica/Rothera",
        "Country":"Rothera"
    },
    {
        "Timezone":"Antarctica/South_Pole",
        "Country":"South Pole"
    },
    {
        "Timezone":"Antarctica/Syowa",
        "Country":"Syowa"
    },
    {
        "Timezone":"Antarctica/Troll",
        "Country":"Troll"
    },
    {
        "Timezone":"Antarctica/Vostok",
        "Country":"Vostok"
    },
    {
        "Timezone":"Arctic/Longyearbyen",
        "Country":"Longyearbyen"
    },
    {
        "Timezone":"Asia/Aden",
        "Country":"Aden"
    },
    {
        "Timezone":"Asia/Almaty",
        "Country":"Almaty"
    },
    {
        "Timezone":"Asia/Amman",
        "Country":"Amman"
    },
    {
        "Timezone":"Asia/Anadyr",
        "Country":"Anadyr"
    },
    {
        "Timezone":"Asia/Aqtau",
        "Country":"Aqtau"
    },
    {
        "Timezone":"Asia/Aqtobe",
        "Country":"Aqtobe"
    },
    {
        "Timezone":"Asia/Ashgabat",
        "Country":"Ashgabat"
    },
    {
        "Timezone":"Asia/Ashkhabad",
        "Country":"Ashkhabad"
    },
    {
        "Timezone":"Asia/Atyrau",
        "Country":"Atyrau"
    },
    {
        "Timezone":"Asia/Baghdad",
        "Country":"Baghdad"
    },
    {
        "Timezone":"Asia/Bahrain",
        "Country":"Bahrain"
    },
    {
        "Timezone":"Asia/Baku",
        "Country":"Baku"
    },
    {
        "Timezone":"Asia/Bangkok",
        "Country":"Bangkok"
    },
    {
        "Timezone":"Asia/Barnaul",
        "Country":"Barnaul"
    },
    {
        "Timezone":"Asia/Beirut",
        "Country":"Beirut"
    },
    {
        "Timezone":"Asia/Bishkek",
        "Country":"Bishkek"
    },
    {
        "Timezone":"Asia/Brunei",
        "Country":"Brunei"
    },
    {
        "Timezone":"Asia/Calcutta",
        "Country":"Calcutta"
    },
    {
        "Timezone":"Asia/Chita",
        "Country":"Chita"
    },
    {
        "Timezone":"Asia/Choibalsan",
        "Country":"Choibalsan"
    },
    {
        "Timezone":"Asia/Chongqing",
        "Country":"Chongqing"
    },
    {
        "Timezone":"Asia/Chungking",
        "Country":"Chungking"
    },
    {
        "Timezone":"Asia/Colombo",
        "Country":"Colombo"
    },
    {
        "Timezone":"Asia/Dacca",
        "Country":"Dacca"
    },
    {
        "Timezone":"Asia/Damascus",
        "Country":"Damascus"
    },
    {
        "Timezone":"Asia/Dhaka",
        "Country":"Dhaka"
    },
    {
        "Timezone":"Asia/Dili",
        "Country":"Dili"
    },
    {
        "Timezone":"Asia/Dubai",
        "Country":"Dubai"
    },
    {
        "Timezone":"Asia/Dushanbe",
        "Country":"Dushanbe"
    },
    {
        "Timezone":"Asia/Famagusta",
        "Country":"Famagusta"
    },
    {
        "Timezone":"Asia/Gaza",
        "Country":"Gaza"
    },
    {
        "Timezone":"Asia/Harbin",
        "Country":"Harbin"
    },
    {
        "Timezone":"Asia/Hebron",
        "Country":"Hebron"
    },
    {
        "Timezone":"Asia/Ho_Chi_Minh",
        "Country":"Ho Chi Minh"
    },
    {
        "Timezone":"Asia/Hong_Kong",
        "Country":"Hong Kong"
    },
    {
        "Timezone":"Asia/Hovd",
        "Country":"Hovd"
    },
    {
        "Timezone":"Asia/Irkutsk",
        "Country":"Irkutsk"
    },
    {
        "Timezone":"Asia/Istanbul",
        "Country":"Istanbul"
    },
    {
        "Timezone":"Asia/Jakarta",
        "Country":"Jakarta"
    },
    {
        "Timezone":"Asia/Jayapura",
        "Country":"Jayapura"
    },
    {
        "Timezone":"Asia/Jerusalem",
        "Country":"Jerusalem"
    },
    {
        "Timezone":"Asia/Kabul",
        "Country":"Kabul"
    },
    {
        "Timezone":"Asia/Kamchatka",
        "Country":"Kamchatka"
    },
    {
        "Timezone":"Asia/Karachi",
        "Country":"Karachi"
    },
    {
        "Timezone":"Asia/Kashgar",
        "Country":"Kashgar"
    },
    {
        "Timezone":"Asia/Kathmandu",
        "Country":"Kathmandu"
    },
    {
        "Timezone":"Asia/Katmandu",
        "Country":"Katmandu"
    },
    {
        "Timezone":"Asia/Khandyga",
        "Country":"Khandyga"
    },
    {
        "Timezone":"Asia/Kolkata",
        "Country":"Kolkata"
    },
    {
        "Timezone":"Asia/Krasnoyarsk",
        "Country":"Krasnoyarsk"
    },
    {
        "Timezone":"Asia/Kuala_Lumpur",
        "Country":"Kuala Lumpur"
    },
    {
        "Timezone":"Asia/Kuching",
        "Country":"Kuching"
    },
    {
        "Timezone":"Asia/Kuwait",
        "Country":"Kuwait"
    },
    {
        "Timezone":"Asia/Macao",
        "Country":"Macao"
    },
    {
        "Timezone":"Asia/Macau",
        "Country":"Macau"
    },
    {
        "Timezone":"Asia/Magadan",
        "Country":"Magadan"
    },
    {
        "Timezone":"Asia/Makassar",
        "Country":"Makassar"
    },
    {
        "Timezone":"Asia/Manila",
        "Country":"Manila"
    },
    {
        "Timezone":"Asia/Muscat",
        "Country":"Muscat"
    },
    {
        "Timezone":"Asia/Nicosia",
        "Country":"Nicosia"
    },
    {
        "Timezone":"Asia/Novokuznetsk",
        "Country":"Novokuznetsk"
    },
    {
        "Timezone":"Asia/Novosibirsk",
        "Country":"Novosibirsk"
    },
    {
        "Timezone":"Asia/Omsk",
        "Country":"Omsk"
    },
    {
        "Timezone":"Asia/Oral",
        "Country":"Oral"
    },
    {
        "Timezone":"Asia/Phnom_Penh",
        "Country":"Phnom Penh"
    },
    {
        "Timezone":"Asia/Pontianak",
        "Country":"Pontianak"
    },
    {
        "Timezone":"Asia/Pyongyang",
        "Country":"Pyongyang"
    },
    {
        "Timezone":"Asia/Qatar",
        "Country":"Qatar"
    },
    {
        "Timezone":"Asia/Qostanay",
        "Country":"Qostanay"
    },
    {
        "Timezone":"Asia/Qyzylorda",
        "Country":"Qyzylorda"
    },
    {
        "Timezone":"Asia/Rangoon",
        "Country":"Rangoon"
    },
    {
        "Timezone":"Asia/Riyadh",
        "Country":"Riyadh"
    },
    {
        "Timezone":"Asia/Saigon",
        "Country":"Saigon"
    },
    {
        "Timezone":"Asia/Sakhalin",
        "Country":"Sakhalin"
    },
    {
        "Timezone":"Asia/Samarkand",
        "Country":"Samarkand"
    },
    {
        "Timezone":"Asia/Seoul",
        "Country":"Seoul"
    },
    {
        "Timezone":"Asia/Shanghai",
        "Country":"Shanghai"
    },
    {
        "Timezone":"Asia/Singapore",
        "Country":"Singapore"
    },
    {
        "Timezone":"Asia/Srednekolymsk",
        "Country":"Srednekolymsk"
    },
    {
        "Timezone":"Asia/Taipei",
        "Country":"Taipei"
    },
    {
        "Timezone":"Asia/Tashkent",
        "Country":"Tashkent"
    },
    {
        "Timezone":"Asia/Tbilisi",
        "Country":"Tbilisi"
    },
    {
        "Timezone":"Asia/Tehran",
        "Country":"Tehran"
    },
    {
        "Timezone":"Asia/Tel_Aviv",
        "Country":"Tel Aviv"
    },
    {
        "Timezone":"Asia/Thimbu",
        "Country":"Thimbu"
    },
    {
        "Timezone":"Asia/Thimphu",
        "Country":"Thimphu"
    },
    {
        "Timezone":"Asia/Tokyo",
        "Country":"Tokyo"
    },
    {
        "Timezone":"Asia/Tomsk",
        "Country":"Tomsk"
    },
    {
        "Timezone":"Asia/Ujung_Pandang",
        "Country":"Ujung Pandang"
    },
    {
        "Timezone":"Asia/Ulaanbaatar",
        "Country":"Ulaanbaatar"
    },
    {
        "Timezone":"Asia/Ulan_Bator",
        "Country":"Ulan Bator"
    },
    {
        "Timezone":"Asia/Urumqi",
        "Country":"Urumqi"
    },
    {
        "Timezone":"Asia/Ust-Nera",
        "Country":"Ust-Nera"
    },
    {
        "Timezone":"Asia/Vientiane",
        "Country":"Vientiane"
    },
    {
        "Timezone":"Asia/Vladivostok",
        "Country":"Vladivostok"
    },
    {
        "Timezone":"Asia/Yakutsk",
        "Country":"Yakutsk"
    },
    {
        "Timezone":"Asia/Yangon",
        "Country":"Yangon"
    },
    {
        "Timezone":"Asia/Yekaterinburg",
        "Country":"Yekaterinburg"
    },
    {
        "Timezone":"Asia/Yerevan",
        "Country":"Yerevan"
    },
    {
        "Timezone":"Atlantic/Azores",
        "Country":"Azores"
    },
    {
        "Timezone":"Atlantic/Bermuda",
        "Country":"Bermuda"
    },
    {
        "Timezone":"Atlantic/Canary",
        "Country":"Canary"
    },
    {
        "Timezone":"Atlantic/Cape_Verde",
        "Country":"Cape Verde"
    },
    {
        "Timezone":"Atlantic/Faeroe",
        "Country":"Faeroe"
    },
    {
        "Timezone":"Atlantic/Faroe",
        "Country":"Faroe"
    },
    {
        "Timezone":"Atlantic/Jan_Mayen",
        "Country":"Jan Mayen"
    },
    {
        "Timezone":"Atlantic/Madeira",
        "Country":"Madeira"
    },
    {
        "Timezone":"Atlantic/Reykjavik",
        "Country":"Reykjavik"
    },
    {
        "Timezone":"Atlantic/South_Georgia",
        "Country":"South Georgia"
    },
    {
        "Timezone":"Atlantic/St_Helena",
        "Country":"St Helena"
    },
    {
        "Timezone":"Atlantic/Stanley",
        "Country":"Stanley"
    },
    {
        "Timezone":"Australia/ACT",
        "Country":"ACT"
    },
    {
        "Timezone":"Australia/Adelaide",
        "Country":"Adelaide"
    },
    {
        "Timezone":"Australia/Brisbane",
        "Country":"Brisbane"
    },
    {
        "Timezone":"Australia/Broken_Hill",
        "Country":"Broken Hill"
    },
    {
        "Timezone":"Australia/Canberra",
        "Country":"Canberra"
    },
    {
        "Timezone":"Australia/Currie",
        "Country":"Currie"
    },
    {
        "Timezone":"Australia/Darwin",
        "Country":"Darwin"
    },
    {
        "Timezone":"Australia/Eucla",
        "Country":"Eucla"
    },
    {
        "Timezone":"Australia/Hobart",
        "Country":"Hobart"
    },
    {
        "Timezone":"Australia/LHI",
        "Country":"LHI"
    },
    {
        "Timezone":"Australia/Lindeman",
        "Country":"Lindeman"
    },
    {
        "Timezone":"Australia/Lord_Howe",
        "Country":"Lord Howe"
    },
    {
        "Timezone":"Australia/Melbourne",
        "Country":"Melbourne"
    },
    {
        "Timezone":"Australia/NSW",
        "Country":"NSW"
    },
    {
        "Timezone":"Australia/North",
        "Country":"North"
    },
    {
        "Timezone":"Australia/Perth",
        "Country":"Perth"
    },
    {
        "Timezone":"Australia/Queensland",
        "Country":"Queensland"
    },
    {
        "Timezone":"Australia/South",
        "Country":"South"
    },
    {
        "Timezone":"Australia/Sydney",
        "Country":"Sydney"
    },
    {
        "Timezone":"Australia/Tasmania",
        "Country":"Tasmania"
    },
    {
        "Timezone":"Australia/Victoria",
        "Country":"Victoria"
    },
    {
        "Timezone":"Australia/West",
        "Country":"West"
    },
    {
        "Timezone":"Australia/Yancowinna",
        "Country":"Yancowinna"
    },
    {
        "Timezone":"Brazil/Acre",
        "Country":"Acre"
    },
    {
        "Timezone":"Brazil/DeNoronha",
        "Country":"DeNoronha"
    },
    {
        "Timezone":"Brazil/East",
        "Country":"East"
    },
    {
        "Timezone":"Brazil/West",
        "Country":"West"
    },
    {
        "Timezone":"CET",
        "Country":"CET"
    },
    {
        "Timezone":"CST6CDT",
        "Country":"CST6CDT"
    },
    {
        "Timezone":"Canada/Atlantic",
        "Country":"Atlantic"
    },
    {
        "Timezone":"Canada/Central",
        "Country":"Central"
    },
    {
        "Timezone":"Canada/Eastern",
        "Country":"Eastern"
    },
    {
        "Timezone":"Canada/Mountain",
        "Country":"Mountain"
    },
    {
        "Timezone":"Canada/Newfoundland",
        "Country":"Newfoundland"
    },
    {
        "Timezone":"Canada/Pacific",
        "Country":"Pacific"
    },
    {
        "Timezone":"Canada/Saskatchewan",
        "Country":"Saskatchewan"
    },
    {
        "Timezone":"Canada/Yukon",
        "Country":"Yukon"
    },
    {
        "Timezone":"Chile/Continental",
        "Country":"Continental"
    },
    {
        "Timezone":"Chile/EasterIsland",
        "Country":"EasterIsland"
    },
    {
        "Timezone":"Cuba",
        "Country":"Cuba"
    },
    {
        "Timezone":"EET",
        "Country":"EET"
    },
    {
        "Timezone":"EST",
        "Country":"EST"
    },
    {
        "Timezone":"EST5EDT",
        "Country":"EST5EDT"
    },
    {
        "Timezone":"Egypt",
        "Country":"Egypt"
    },
    {
        "Timezone":"Eire",
        "Country":"Eire"
    },
    {
        "Timezone":"Etc/GMT",
        "Country":"GMT"
    },
    {
        "Timezone":"Etc/GMT+0",
        "Country":"GMT+0"
    },
    {
        "Timezone":"Etc/GMT+1",
        "Country":"GMT+1"
    },
    {
        "Timezone":"Etc/GMT+10",
        "Country":"GMT+10"
    },
    {
        "Timezone":"Etc/GMT+11",
        "Country":"GMT+11"
    },
    {
        "Timezone":"Etc/GMT+12",
        "Country":"GMT+12"
    },
    {
        "Timezone":"Etc/GMT+2",
        "Country":"GMT+2"
    },
    {
        "Timezone":"Etc/GMT+3",
        "Country":"GMT+3"
    },
    {
        "Timezone":"Etc/GMT+4",
        "Country":"GMT+4"
    },
    {
        "Timezone":"Etc/GMT+5",
        "Country":"GMT+5"
    },
    {
        "Timezone":"Etc/GMT+6",
        "Country":"GMT+6"
    },
    {
        "Timezone":"Etc/GMT+7",
        "Country":"GMT+7"
    },
    {
        "Timezone":"Etc/GMT+8",
        "Country":"GMT+8"
    },
    {
        "Timezone":"Etc/GMT+9",
        "Country":"GMT+9"
    },
    {
        "Timezone":"Etc/GMT-0",
        "Country":"GMT-0"
    },
    {
        "Timezone":"Etc/GMT-1",
        "Country":"GMT-1"
    },
    {
        "Timezone":"Etc/GMT-10",
        "Country":"GMT-10"
    },
    {
        "Timezone":"Etc/GMT-11",
        "Country":"GMT-11"
    },
    {
        "Timezone":"Etc/GMT-12",
        "Country":"GMT-12"
    },
    {
        "Timezone":"Etc/GMT-13",
        "Country":"GMT-13"
    },
    {
        "Timezone":"Etc/GMT-14",
        "Country":"GMT-14"
    },
    {
        "Timezone":"Etc/GMT-2",
        "Country":"GMT-2"
    },
    {
        "Timezone":"Etc/GMT-3",
        "Country":"GMT-3"
    },
    {
        "Timezone":"Etc/GMT-4",
        "Country":"GMT-4"
    },
    {
        "Timezone":"Etc/GMT-5",
        "Country":"GMT-5"
    },
    {
        "Timezone":"Etc/GMT-6",
        "Country":"GMT-6"
    },
    {
        "Timezone":"Etc/GMT-7",
        "Country":"GMT-7"
    },
    {
        "Timezone":"Etc/GMT-8",
        "Country":"GMT-8"
    },
    {
        "Timezone":"Etc/GMT-9",
        "Country":"GMT-9"
    },
    {
        "Timezone":"Etc/GMT0",
        "Country":"GMT0"
    },
    {
        "Timezone":"Etc/Greenwich",
        "Country":"Greenwich"
    },
    {
        "Timezone":"Etc/UCT",
        "Country":"UCT"
    },
    {
        "Timezone":"Etc/UTC",
        "Country":"UTC"
    },
    {
        "Timezone":"Etc/Universal",
        "Country":"Universal"
    },
    {
        "Timezone":"Etc/Zulu",
        "Country":"Zulu"
    },
    {
        "Timezone":"Europe/Amsterdam",
        "Country":"Amsterdam"
    },
    {
        "Timezone":"Europe/Andorra",
        "Country":"Andorra"
    },
    {
        "Timezone":"Europe/Astrakhan",
        "Country":"Astrakhan"
    },
    {
        "Timezone":"Europe/Athens",
        "Country":"Athens"
    },
    {
        "Timezone":"Europe/Belfast",
        "Country":"Belfast"
    },
    {
        "Timezone":"Europe/Belgrade",
        "Country":"Belgrade"
    },
    {
        "Timezone":"Europe/Berlin",
        "Country":"Berlin"
    },
    {
        "Timezone":"Europe/Bratislava",
        "Country":"Bratislava"
    },
    {
        "Timezone":"Europe/Brussels",
        "Country":"Brussels"
    },
    {
        "Timezone":"Europe/Bucharest",
        "Country":"Bucharest"
    },
    {
        "Timezone":"Europe/Budapest",
        "Country":"Budapest"
    },
    {
        "Timezone":"Europe/Busingen",
        "Country":"Busingen"
    },
    {
        "Timezone":"Europe/Chisinau",
        "Country":"Chisinau"
    },
    {
        "Timezone":"Europe/Copenhagen",
        "Country":"Copenhagen"
    },
    {
        "Timezone":"Europe/Dublin",
        "Country":"Dublin"
    },
    {
        "Timezone":"Europe/Gibraltar",
        "Country":"Gibraltar"
    },
    {
        "Timezone":"Europe/Guernsey",
        "Country":"Guernsey"
    },
    {
        "Timezone":"Europe/Helsinki",
        "Country":"Helsinki"
    },
    {
        "Timezone":"Europe/Isle_of_Man",
        "Country":"Isle of Man"
    },
    {
        "Timezone":"Europe/Istanbul",
        "Country":"Istanbul"
    },
    {
        "Timezone":"Europe/Jersey",
        "Country":"Jersey"
    },
    {
        "Timezone":"Europe/Kaliningrad",
        "Country":"Kaliningrad"
    },
    {
        "Timezone":"Europe/Kiev",
        "Country":"Kiev"
    },
    {
        "Timezone":"Europe/Kirov",
        "Country":"Kirov"
    },
    {
        "Timezone":"Europe/Kyiv",
        "Country":"Kyiv"
    },
    {
        "Timezone":"Europe/Lisbon",
        "Country":"Lisbon"
    },
    {
        "Timezone":"Europe/Ljubljana",
        "Country":"Ljubljana"
    },
    {
        "Timezone":"Europe/London",
        "Country":"London"
    },
    {
        "Timezone":"Europe/Luxembourg",
        "Country":"Luxembourg"
    },
    {
        "Timezone":"Europe/Madrid",
        "Country":"Madrid"
    },
    {
        "Timezone":"Europe/Malta",
        "Country":"Malta"
    },
    {
        "Timezone":"Europe/Mariehamn",
        "Country":"Mariehamn"
    },
    {
        "Timezone":"Europe/Minsk",
        "Country":"Minsk"
    },
    {
        "Timezone":"Europe/Monaco",
        "Country":"Monaco"
    },
    {
        "Timezone":"Europe/Moscow",
        "Country":"Moscow"
    },
    {
        "Timezone":"Europe/Nicosia",
        "Country":"Nicosia"
    },
    {
        "Timezone":"Europe/Oslo",
        "Country":"Oslo"
    },
    {
        "Timezone":"Europe/Paris",
        "Country":"Paris"
    },
    {
        "Timezone":"Europe/Podgorica",
        "Country":"Podgorica"
    },
    {
        "Timezone":"Europe/Prague",
        "Country":"Prague"
    },
    {
        "Timezone":"Europe/Riga",
        "Country":"Riga"
    },
    {
        "Timezone":"Europe/Rome",
        "Country":"Rome"
    },
    {
        "Timezone":"Europe/Samara",
        "Country":"Samara"
    },
    {
        "Timezone":"Europe/San_Marino",
        "Country":"San Marino"
    },
    {
        "Timezone":"Europe/Sarajevo",
        "Country":"Sarajevo"
    },
    {
        "Timezone":"Europe/Saratov",
        "Country":"Saratov"
    },
    {
        "Timezone":"Europe/Simferopol",
        "Country":"Simferopol"
    },
    {
        "Timezone":"Europe/Skopje",
        "Country":"Skopje"
    },
    {
        "Timezone":"Europe/Sofia",
        "Country":"Sofia"
    },
    {
        "Timezone":"Europe/Stockholm",
        "Country":"Stockholm"
    },
    {
        "Timezone":"Europe/Tallinn",
        "Country":"Tallinn"
    },
    {
        "Timezone":"Europe/Tirane",
        "Country":"Tirane"
    },
    {
        "Timezone":"Europe/Tiraspol",
        "Country":"Tiraspol"
    },
    {
        "Timezone":"Europe/Ulyanovsk",
        "Country":"Ulyanovsk"
    },
    {
        "Timezone":"Europe/Uzhgorod",
        "Country":"Uzhgorod"
    },
    {
        "Timezone":"Europe/Vaduz",
        "Country":"Vaduz"
    },
    {
        "Timezone":"Europe/Vatican",
        "Country":"Vatican"
    },
    {
        "Timezone":"Europe/Vienna",
        "Country":"Vienna"
    },
    {
        "Timezone":"Europe/Vilnius",
        "Country":"Vilnius"
    },
    {
        "Timezone":"Europe/Volgograd",
        "Country":"Volgograd"
    },
    {
        "Timezone":"Europe/Warsaw",
        "Country":"Warsaw"
    },
    {
        "Timezone":"Europe/Zagreb",
        "Country":"Zagreb"
    },
    {
        "Timezone":"Europe/Zaporozhye",
        "Country":"Zaporozhye"
    },
    {
        "Timezone":"Europe/Zurich",
        "Country":"Zurich"
    },
    {
        "Timezone":"GB",
        "Country":"GB"
    },
    {
        "Timezone":"GB-Eire",
        "Country":"GB-Eire"
    },
    {
        "Timezone":"GMT",
        "Country":"GMT"
    },
    {
        "Timezone":"GMT+0",
        "Country":"GMT+0"
    },
    {
        "Timezone":"GMT-0",
        "Country":"GMT-0"
    },
    {
        "Timezone":"GMT0",
        "Country":"GMT0"
    },
    {
        "Timezone":"Greenwich",
        "Country":"Greenwich"
    },
    {
        "Timezone":"HST",
        "Country":"HST"
    },
    {
        "Timezone":"Hongkong",
        "Country":"Hongkong"
    },
    {
        "Timezone":"Iceland",
        "Country":"Iceland"
    },
    {
        "Timezone":"Indian/Antananarivo",
        "Country":"Antananarivo"
    },
    {
        "Timezone":"Indian/Chagos",
        "Country":"Chagos"
    },
    {
        "Timezone":"Indian/Christmas",
        "Country":"Christmas"
    },
    {
        "Timezone":"Indian/Cocos",
        "Country":"Cocos"
    },
    {
        "Timezone":"Indian/Comoro",
        "Country":"Comoro"
    },
    {
        "Timezone":"Indian/Kerguelen",
        "Country":"Kerguelen"
    },
    {
        "Timezone":"Indian/Mahe",
        "Country":"Mahe"
    },
    {
        "Timezone":"Indian/Maldives",
        "Country":"Maldives"
    },
    {
        "Timezone":"Indian/Mauritius",
        "Country":"Mauritius"
    },
    {
        "Timezone":"Indian/Mayotte",
        "Country":"Mayotte"
    },
    {
        "Timezone":"Indian/Reunion",
        "Country":"Reunion"
    },
    {
        "Timezone":"Iran",
        "Country":"Iran"
    },
    {
        "Timezone":"Israel",
        "Country":"Israel"
    },
    {
        "Timezone":"Jamaica",
        "Country":"Jamaica"
    },
    {
        "Timezone":"Japan",
        "Country":"Japan"
    },
    {
        "Timezone":"Kwajalein",
        "Country":"Kwajalein"
    },
    {
        "Timezone":"Libya",
        "Country":"Libya"
    },
    {
        "Timezone":"MET",
        "Country":"MET"
    },
    {
        "Timezone":"MST",
        "Country":"MST"
    },
    {
        "Timezone":"MST7MDT",
        "Country":"MST7MDT"
    },
    {
        "Timezone":"Mexico/BajaNorte",
        "Country":"BajaNorte"
    },
    {
        "Timezone":"Mexico/BajaSur",
        "Country":"BajaSur"
    },
    {
        "Timezone":"Mexico/General",
        "Country":"General"
    },
    {
        "Timezone":"NZ",
        "Country":"NZ"
    },
    {
        "Timezone":"NZ-CHAT",
        "Country":"NZ-CHAT"
    },
    {
        "Timezone":"Navajo",
        "Country":"Navajo"
    },
    {
        "Timezone":"PRC",
        "Country":"PRC"
    },
    {
        "Timezone":"PST8PDT",
        "Country":"PST8PDT"
    },
    {
        "Timezone":"Pacific/Apia",
        "Country":"Apia"
    },
    {
        "Timezone":"Pacific/Auckland",
        "Country":"Auckland"
    },
    {
        "Timezone":"Pacific/Bougainville",
        "Country":"Bougainville"
    },
    {
        "Timezone":"Pacific/Chatham",
        "Country":"Chatham"
    },
    {
        "Timezone":"Pacific/Chuuk",
        "Country":"Chuuk"
    },
    {
        "Timezone":"Pacific/Easter",
        "Country":"Easter"
    },
    {
        "Timezone":"Pacific/Efate",
        "Country":"Efate"
    },
    {
        "Timezone":"Pacific/Enderbury",
        "Country":"Enderbury"
    },
    {
        "Timezone":"Pacific/Fakaofo",
        "Country":"Fakaofo"
    },
    {
        "Timezone":"Pacific/Fiji",
        "Country":"Fiji"
    },
    {
        "Timezone":"Pacific/Funafuti",
        "Country":"Funafuti"
    },
    {
        "Timezone":"Pacific/Galapagos",
        "Country":"Galapagos"
    },
    {
        "Timezone":"Pacific/Gambier",
        "Country":"Gambier"
    },
    {
        "Timezone":"Pacific/Guadalcanal",
        "Country":"Guadalcanal"
    },
    {
        "Timezone":"Pacific/Guam",
        "Country":"Guam"
    },
    {
        "Timezone":"Pacific/Honolulu",
        "Country":"Honolulu"
    },
    {
        "Timezone":"Pacific/Johnston",
        "Country":"Johnston"
    },
    {
        "Timezone":"Pacific/Kanton",
        "Country":"Kanton"
    },
    {
        "Timezone":"Pacific/Kiritimati",
        "Country":"Kiritimati"
    },
    {
        "Timezone":"Pacific/Kosrae",
        "Country":"Kosrae"
    },
    {
        "Timezone":"Pacific/Kwajalein",
        "Country":"Kwajalein"
    },
    {
        "Timezone":"Pacific/Majuro",
        "Country":"Majuro"
    },
    {
        "Timezone":"Pacific/Marquesas",
        "Country":"Marquesas"
    },
    {
        "Timezone":"Pacific/Midway",
        "Country":"Midway"
    },
    {
        "Timezone":"Pacific/Nauru",
        "Country":"Nauru"
    },
    {
        "Timezone":"Pacific/Niue",
        "Country":"Niue"
    },
    {
        "Timezone":"Pacific/Norfolk",
        "Country":"Norfolk"
    },
    {
        "Timezone":"Pacific/Noumea",
        "Country":"Noumea"
    },
    {
        "Timezone":"Pacific/Pago_Pago",
        "Country":"Pago Pago"
    },
    {
        "Timezone":"Pacific/Palau",
        "Country":"Palau"
    },
    {
        "Timezone":"Pacific/Pitcairn",
        "Country":"Pitcairn"
    },
    {
        "Timezone":"Pacific/Pohnpei",
        "Country":"Pohnpei"
    },
    {
        "Timezone":"Pacific/Ponape",
        "Country":"Ponape"
    },
    {
        "Timezone":"Pacific/Port_Moresby",
        "Country":"Port Moresby"
    },
    {
        "Timezone":"Pacific/Rarotonga",
        "Country":"Rarotonga"
    },
    {
        "Timezone":"Pacific/Saipan",
        "Country":"Saipan"
    },
    {
        "Timezone":"Pacific/Samoa",
        "Country":"Samoa"
    },
    {
        "Timezone":"Pacific/Tahiti",
        "Country":"Tahiti"
    },
    {
        "Timezone":"Pacific/Tarawa",
        "Country":"Tarawa"
    },
    {
        "Timezone":"Pacific/Tongatapu",
        "Country":"Tongatapu"
    },
    {
        "Timezone":"Pacific/Truk",
        "Country":"Truk"
    },
    {
        "Timezone":"Pacific/Wake",
        "Country":"Wake"
    },
    {
        "Timezone":"Pacific/Wallis",
        "Country":"Wallis"
    },
    {
        "Timezone":"Pacific/Yap",
        "Country":"Yap"
    },
    {
        "Timezone":"Poland",
        "Country":"Poland"
    },
    {
        "Timezone":"Portugal",
        "Country":"Portugal"
    },
    {
        "Timezone":"ROC",
        "Country":"ROC"
    },
    {
        "Timezone":"ROK",
        "Country":"ROK"
    },
    {
        "Timezone":"Singapore",
        "Country":"Singapore"
    },
    {
        "Timezone":"Turkey",
        "Country":"Turkey"
    },
    {
        "Timezone":"UCT",
        "Country":"UCT"
    },
    {
        "Timezone":"US/Alaska",
        "Country":"Alaska"
    },
    {
        "Timezone":"US/Aleutian",
        "Country":"Aleutian"
    },
    {
        "Timezone":"US/Arizona",
        "Country":"Arizona"
    },
    {
        "Timezone":"US/Central",
        "Country":"Central"
    },
    {
        "Timezone":"US/East-Indiana",
        "Country":"East-Indiana"
    },
    {
        "Timezone":"US/Eastern",
        "Country":"Eastern"
    },
    {
        "Timezone":"US/Hawaii",
        "Country":"Hawaii"
    },
    {
        "Timezone":"US/Indiana-Starke",
        "Country":"Indiana-Starke"
    },
    {
        "Timezone":"US/Michigan",
        "Country":"Michigan"
    },
    {
        "Timezone":"US/Mountain",
        "Country":"Mountain"
    },
    {
        "Timezone":"US/Pacific",
        "Country":"Pacific"
    },
    {
        "Timezone":"US/Samoa",
        "Country":"Samoa"
    },
    {
        "Timezone":"UTC",
        "Country":"UTC"
    },
    {
        "Timezone":"Universal",
        "Country":"Universal"
    },
    {
        "Timezone":"W-SU",
        "Country":"W-SU"
    },
    {
        "Timezone":"WET",
        "Country":"WET"
    },
    {
        "Timezone":"Zulu",
        "Country":"Zulu"
    }
]